baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "hugo-theme-learn"

[params]
    themeVariant = "blue"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]