baseURL = 'https://mumby0168.github.io'
languageCode = 'en-us'
title = 'Azure Cert Notes'

theme = "hugo-theme-learn"

[params]
    themeVariant = "blue"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]